language: ruby

dist: bionic

cache:
  bundler: true

script: bundle exec rake

jobs:
  include:
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.7
    - rvm: 2.7.1
      name: "RuboCop"
      script: bundle exec rubocop

branches:
  only:
    - master
